Trained model + Model script for ResNet50
bhhoang/DL-Resnet50 pull request #1
Opened 2023-12-07 07:22 UTC by dangdd2003

# Models
- 25 epochs trained model for classify ant and bee
- 30 epochs trained model for classify 535 bird species
# Script
- ant - bee model script
- bird species model script

2023-12-07 07:29 UTC, bhhoang requested changes

2023-12-07 07:29 UTC, bhhoang commented on README.md
> +- Birds 535 species Dataset: https://www.kaggle.com/datasets/gpiosenka/100-bird-species
*525 species :))

2023-12-07 07:31 UTC, dangdd2003 commented on README.md
> +- Birds 535 species Dataset: https://www.kaggle.com/datasets/gpiosenka/100-bird-species
thi m sua lai, m sua dc ma :+1:

2023-12-07 07:33 UTC, bhhoang commented on README.md
> +- Birds 535 species Dataset: https://www.kaggle.com/datasets/gpiosenka/100-bird-species
M sua di

2023-12-07 07:37 UTC, dangdd2003 reviewed
fix 535 species -> 525 species

2023-12-09 07:46 UTC, bhhoang approved these changes

2023-12-09 07:46 UTC, merged